export default [
  {
    files: ['src/**/*.js'],
    languageOptions: {
      sourceType: 'module',
      ecmaVersion: 'latest',
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        prompt: 'readonly',
        confirm: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        AbortController: 'readonly',
        crypto: 'readonly',
        URLSearchParams: 'readonly',
        indexedDB: 'readonly',
        require: 'readonly',
        module: 'readonly',
        isFinite: 'readonly',
        isNaN: 'readonly',
        decodeURIComponent: 'readonly',
        EventSource: 'readonly',
      },
    },
    rules: {
      'prefer-const': 'error',
      'no-var': 'warn',
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
    },
  },
];