-- 2026-10-08 — Phase C: Debug report fallback storage.
-- Anonymous INSERT-only table so report-issue.py can store debug logs
-- server-side even when no GITHUB_TOKEN is configured.
-- RLS: anon can INSERT but never SELECT.

CREATE TABLE public.debug_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  log_text text not null,
  page_url text,
  description text
);

alter table public.debug_reports enable row level security;
create policy insert_anon on public.debug_reports for insert to anon with check (true);